# Initial Data Exploration

In [7]:
import pandas as pd

In [8]:
df_rater = pd.read_csv("data/icu_adherence_by_rater.csv")
df_rater

    icu_id  icu_type      rater  clabsi_score  cauti_score  vap_score
0        1   General  HeadNurse         88.24        77.62      72.17
1        1   General  Attending         67.45        71.90      57.39
2        2   General  HeadNurse         62.35        82.86      76.52
3        2   General  Attending         60.00        73.81      84.35
4        3   General  HeadNurse         74.90        80.24      72.17
5        3   General  Attending         71.37        75.24      81.74
6        4   General  HeadNurse         79.80        89.05      68.70
7        4   General  Attending         78.82        92.38      86.09
8        5   General  HeadNurse         70.59        73.33      86.96
9        5   General  Attending         70.98        73.10      87.83
10       6   General  HeadNurse         63.14        60.48      48.70
11       6   General  Attending         75.88        70.00      87.83
12       7   General  HeadNurse         69.22        70.24      67.39
13       7   General  Attending         69.80        70.24      68.70
14       8   General  HeadNurse         70.59        86.67      67.83
15       8   General  Attending         69.61        86.67      67.39
16       9   General  HeadNurse         64.71        70.95      68.26
17       9   General  Attending         64.12        70.95      67.39
18      10  Surgical  HeadNurse         88.63        87.14      64.35
19      10  Surgical  Attending         89.22        86.90      68.70
20      11  Surgical  HeadNurse         90.00        84.76      74.78
21      11  Surgical  Attending         89.41        88.10      70.43
22      12  Surgical  HeadNurse         91.37        83.10      73.91
23      12  Surgical  Attending         90.59        85.48      75.65
24      13  Surgical  HeadNurse         91.57        83.81      64.35
25      13  Surgical  Attending         91.37        82.38      69.57
26      14  Surgical  HeadNurse         89.61        93.33      75.65
27      14  Surgical  Attending         89.61        94.52      75.65
28      15  Surgical  HeadNurse         91.76        92.86      76.09
29      15  Surgical  Attending         91.96        94.29      76.52
30      16  Surgical  HeadNurse         85.49        82.86      72.17
31      16  Surgical  Attending         86.27        82.86      73.04
32      17  Surgical  HeadNurse         38.04        79.05      70.43
33      17  Surgical  Attending         81.18        87.62      75.65
34      18   Medical  HeadNurse         88.63        90.71      79.13
35      18   Medical  Attending         88.63        90.71      83.48
36      19   Medical  HeadNurse         86.86        90.95      84.35
37      19   Medical  Attending         84.71        90.95      82.17
38      20   Medical  HeadNurse         68.63        76.67      68.26
39      20   Medical  Attending         67.45        75.71      67.39

In [9]:
df_rater.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   icu_id        40 non-null     int64
 1   icu_type      40 non-null     object
 2   rater         40 non-null     object
 3   clabsi_score  40 non-null     float64
 4   cauti_score   40 non-null     float64
 5   vap_score     40 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.0+ KB

In [10]:
df_items = pd.read_csv("data/icu_adherence_by_item.csv")
df_items = df_items.iloc[:, 1:] # drop 1 to 116 indexing
df_items

,item_short_description,icu_1,icu_2,icu_3,icu_4,icu_5,icu_6,icu_7,icu_8,icu_9,...,icu_11,icu_12,icu_13,icu_14,icu_15,icu_16,icu_17,icu_18,icu_19,icu_20
0,cvc_indication_documented,1.0,0.85,1.0,1.0,1.0,0.0,1.0,0.8,1.0,...,1.0,1.0,0.0,0.8,0.9,0.9,1.0,0.95,0.8,0.85
1,cvc_guideline_availability,0.5,0.50,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.5,0.5,0.0,1.00,0.0,0.00
2,cvc_initial_staff_training,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,0.5,0.5,0.5,1.00,1.0,1.00
3,cvc_refresher_training,0.0,0.00,0.5,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,0.5,0.5,0.0,0.00,0.0,0.00
4,cvc_daily_chg_bathing_icu,0.5,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.5,...,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,vap_avoid_silver_coated_ett,1.0,0.50,0.5,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.0,1.00
112,vap_avoid_kinetic_beds,0.5,1.00,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1.0,1.0,0.0,1.0,1.0,0.5,1.0,0.00,1.0,1.00
113,vap_avoid_prone_positioning_routine,1.0,0.50,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.00,1.0,1.00
114,vap_avoid_grv_monitoring,0.0,1.00,0.5,0.5,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.00,1.0,0.00
115,vap_avoid_early_parenteral_nutrition,0.5,1.00,1.0,1.0,0.0,0.5,1.0,1.0,1.0,...,0.0,0.0,1.0,0.5,0.5,0.5,0.5,1.00,0.5,1.00

In [11]:
df_items.describe().round(3)

,icu_1,icu_2,icu_3,icu_4,icu_5,icu_6,icu_7,icu_8,icu_9,icu_10,icu_11,icu_12,icu_13,icu_14,icu_15,icu_16,icu_17,icu_18,icu_19,icu_20
count,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000,116.000
mean,0.741,0.712,0.756,0.831,0.838,0.851,0.853,0.879,0.872,0.836,0.884,0.894,0.822,0.750,0.709,0.677,0.695,0.756,0.675,0.709
std,0.348,0.305,0.305,0.305,0.322,0.304,0.318,0.251,0.273,0.323,0.283,0.281,0.310,0.341,0.262,0.336,0.404,0.274,0.351,0.321
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.500,0.500,0.575,0.888,0.800,0.850,0.900,0.800,0.900,0.800,1.000,1.000,0.800,0.600,0.500,0.500,0.500,0.600,0.500,0.600
50%,1.000,0.800,0.900,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,0.900,0.700,0.800,1.000,0.800,0.800,0.800
75%,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
max,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000